# Generated by Django 6.0.3 on 2026-03-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_personal_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('BACKEND', 'Back-end'), ('FRONTEND', 'Front-end'), ('FULLSTACK', 'Full-stack'), ('DATAIA', 'Data & IA')], default='BACKEND', max_length=20),
        ),
    ]
