# Generated by Django 6.0.3 on 2026-03-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('actual', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='experiences/images/')),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('top_techs', models.ManyToManyField(related_name='experiences', to='portfolio.technology')),
            ],
        ),
    ]
